FROM php:7-fpm
# Install modules
ENV PHPREDIS_VERSION=php7
RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz && \
  tar xfz /tmp/redis.tar.gz && \
  rm -r /tmp/redis.tar.gz && \
  mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis && \
  docker-php-ext-install redis 
